routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('/auth/login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/admin', function (){
    return 'you are admin';
})->middleware(['auth','auth.admin']);


Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function (){
    Route::resource('/users', 'UserController',['except' => ['show','create','store']]);
    Route::resource('/screens', 'PantallaController',['except' => ['show','store']]);
});

/*Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function (){
    Route::resource('/users','Admin\UserController',['except' => ['show','create','store']]);
});*/

app/User.php
<?php

namespace GPOVALLAS;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roles(){
        return $this->belongsToMany('GPOVALLAS\Role');
    }

    public function hasManyRoles($roles){
        return null !== $this->roles()->whereIn('name',$roles)->first();
    }

    public function hasAnyRole($roles){
        return null !== $this->roles()->where('name',$roles)->first();
    }

}

app/Http/Controllers/Admin/UserController.php
<?php

namespace GPOVALLAS\Http\Controllers\Admin;

use GPOVALLAS\User;
use Illuminate\Http\Request;
use GPOVALLAS\Http\Controllers\Controller;
use GPOVALLAS\Role;
use Illuminate\Support\Facades\Auth;


class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.users.index')->with('users',User::paginate(10));
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(Auth::user()->id == $id){
            return redirect()->route('admin.users.index')->with('warning','El usuario no puede ser editado');
        }

        return view('admin.users.edit')->with(['user' => User::find($id), 'roles' => Role::all()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if(Auth::user()->id == $id){
            return redirect()->route('admin.users.index')->with('warning','El usuario no pudo ser editado');
        }

        $user = User::find($id);
        $user->roles()->sync($request->roles);


        return redirect()->route('admin.users.index')->with('success','El usuario ha sido editado correctamente');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(Auth::user()->id == $id){
            return redirect()->route('admin.users.index')->with('warning','El usuario no puede ser eliminado por si mismo');
        }
        $user = User::find($id);

        if($user){
            $user->roles()->detach();
            $user->delete();
            return redirect()->route('admin.users.index')->with('success','El usuario se ha eliminado correctamente');
        }

        return redirect()->route('admin.users.index')->with('Warning','El usuario no pudo ser Eliminado');
    }
}

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header"> Usuario {{$user->name}} </div>
                    <div class="card-body">
                        <form action="{{ route('admin.users.update', ['user' => $user->id]) }}" method="POST">

                            @csrf

                            {{method_field('PUT')}}

                            @foreach($roles as $role)
                                <div class="form-check">
                                    <input type="checkbox" name="roles[]" value="{{ $role->id }}" {{$user->hasAnyRole($role->name) ?'checked':''}}>
                                    <label>{{$role->name}}</label>
                                </div>
                                @endforeach

                            <button type="submit" class="btn btn-primary">Editar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header"> USUARIOS </div>
                    <div class="card-body">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th scope="col">Nombre</th>
                                <th scope="col">Email</th>
                                <th scope="col">Roles</th>
                                <th scope="col">Acciones</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($users as $user)
                                <tr>
                                    <th>{{$user->name}}</th>
                                    <th>{{$user->email}}</th>
                                    <th>{{implode(' ,',$user->roles()->get()->pluck('name')->toArray())}}</th>
                                    <th>
                                        <a href="{{route('admin.users.edit',$user->id)}}" class="float-left">
                                            <button type="button" class="btn btn-primary btn-sm">Editar</button>
                                        </a>
                                        <form action="{{ route('admin.users.destroy', $user->id) }}" method="POST" class="float-left">
                                            @csrf
                                            {{ method_field('DELETE') }}
                                            <button type="submit" class="btn btn-danger btn-sm">Borrar</button>
                                        </form>
                                    </th>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                        {{$users->links()}}
                    </div>
                </div>
            </div>
        </div>
    </div>
    @endsection