routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('/auth/login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/admin', function (){
    return 'you are admin';
})->middleware(['auth','auth.admin']);


Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function (){
    Route::resource('/users', 'UserController',['except' => ['show','create','store']]);
    Route::resource('/screens', 'PantallaController',['except' => ['show','store']]);
});

/*Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function (){
    Route::resource('/users','Admin\UserController',['except' => ['show','create','store']]);
});*/

resources/views/admin/screens/alerts.blade.php
@extends('layouts.app',['alerts' => $alerts])

@section('content')
    @asyncWidget('alert_screens')
@endsection

resources/views/admin/screens/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            @foreach($screens as $screen)
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header"> Pantalla {{$screen->codigo}}</div>
                    <div class="card-body">
                        <form enctype="multipart/form-data" action="{{ route('admin.screens.update', ['screen' => $screen->id]) }}" method="POST">

                            @csrf

                            {{method_field('PUT')}}
                            <p>{{$screen->codigo}}</p>
                            <p>{{$screen->id}}</p>
                            <div class="form-group row">
                                <label for="picture" class="col-md-4 col-form-label text-md-right">
                                    Selecciona el archivo
                                </label>
                                <div class="col-md-6">
                                    <input id="picture" type="file" class="form-control input-chicmua file" name="picture" value="{{isset($screen->picture) ? $screen->picture:''}}" autofocus/>
                                </div>
                            </div>

                            <button type="submit" class="btn btn-primary">Editar</button>
                        </form>

                    </div>
                </div>
            </div>
            @endforeach
        </div>
    </div>
@endsection